MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "/home/niqbal/trainers/phenobench/mask2former_panoptic_semantic_leaves_synthetic_baseline/model_final.pth"
  # WEIGHTS: "/home/niqbal/datasets/models/model_final_94dc52.pkl"
  PIXEL_MEAN: [124.578, 97.773, 65.357]
  PIXEL_STD: [58.341, 48.268, 37.847]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "BN"  # use syncbn for cityscapes dataset
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  # TRAIN: ("syn_train",)
  TRAIN: ("syn_train_leaves",)
  TEST: ("syn_train_leaves",)
OUTPUT_DIR: "/home/niqbal/trainers/phenobench/mask2former_panoptic_semantic_leaves_synthetic_baseline"
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  MAX_ITER: 5000
  WARMUP_FACTOR: 1.0
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 1024) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 1024
  MAX_SIZE_TEST: 1024
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (1024, 1024) # (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: -1
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "pheno_mask_former_panoptic"
TEST:
  EVAL_PERIOD: 500
  AUG:
    ENABLED: False
    MIN_SIZES: [512, 768, 1024, 1280, 1536, 1792]
    MAX_SIZE: 4096
    FLIP: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2